apiVersion: v1
kind: Secret
metadata:
  name: {{ template "aws-login.fullname" . }}
  labels:
    app: {{ template "aws-login.name" . }}
    chart: {{ template "aws-login.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  AUTH0_DOMAIN: {{ .Values.environment.AUTH0_DOMAIN | b64enc | quote }}
  AUTH0_CLIENT_ID: {{ .Values.environment.AUTH0_CLIENT_ID | b64enc | quote }}
  AUTH0_CLIENT_SECRET: {{ .Values.environment.AUTH0_CLIENT_SECRET | b64enc | quote }}
  AUTH0_CALLBACK_URL: {{ .Values.environment.AUTH0_CALLBACK_URL | b64enc | quote }}
  COOKIE_SECRET: {{ .Values.environment.COOKIE_SECRET | b64enc | quote }}
  AWS_ACCOUNT_ID: {{ .Values.environment.AWS_ACCOUNT_ID | b64enc | quote }}
  ENV: {{ .Values.environment.ENV | b64enc | quote }}
