apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: concourse-{{ .Values.concourse.team }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  github-access-token: {{ .Values.github.accessToken | b64enc | quote }}
  github-webhook-token: {{ .Values.github.webhookToken | b64enc | quote }}
  kubernetes-api-url: {{ .Values.kubernetes.apiUrl | b64enc | quote }}
  kubernetes-ca-cert: {{ .Values.kubernetes.caCert | b64enc | quote }}
  kubernetes-token: {{ .Values.kubernetes.token | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: fly
  namespace: concourse-{{ .Values.concourse.team }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  password: {{ .Values.concourse.password | b64enc | quote }}
  username: {{ .Values.concourse.username | b64enc | quote }}
